<?php
/**
 * @file
 * typeformer.module
 */

/**
 * Implements hook_node_info().
 */
function typeformer_node_info() {
  $items = array(
    'typeform' => array(
      'base' => 'node_content',
      'name' => t('Typeform'),
      'description' => t('Embed your Typeform URLs inside your site domain.'),
      'title_label' => t('Page Title'),
      'has_title' => TRUE,
    ),
  );
  return $items;
}

/**
 * Implements hook_init().
 */
function typeformer_init() {
  // only trigger if a node page
  if (arg(0) == 'node' && !arg(2)) {
    $node = menu_get_object('node');
    // only override if node is a typeform
    if ($node->type == 'typeform') {
      $wrapper = entity_metadata_wrapper('node', $node);
      typeformer_render_html($wrapper->title->value(), $wrapper->field_typeform_url->value());
      drupal_exit();
    }
  }
}

/**
 * Renders the overriden HTML to properly display a full-page iFrame with the
 * loaded Typeform.
 *
 * @param   string $title
 * @param   string $url
 * @return  void
 */
function typeformer_render_html($title, $url) {
  $html = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">'
    . '<html><head> <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"> '
    . '<title>' . check_plain($title) . '</title> <style type="text/css"> html{ margin: 0; height: 100%; overflow: hidden; } '
    . 'iframe{ position: absolute; left:0; right:0; bottom:0; top:0; border:0; } </style></head><body> '
    . '<iframe id="typeform-full" width="100%" height="100%" frameborder="0" src="' . check_url($url) . '"></iframe> '
    . '<script type="text/javascript" src="https://s3-eu-west-1.amazonaws.com/share.typeform.com/embed.js"></script>'
    . '</body></html>';

  print $html;
}
